name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y apktool signapk

    - name: Set Java alternatives
      run: |
        sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac

    - name: Run build script
      run: ./build.sh

