name: 构建 Android 应用

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 设置 Java 环境
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt install -y apktool signapk

    - name: 赋予脚本执行权限
      run: chmod +x build.sh

    - name: 构建应用
      run: ./build.sh

    - name: 上传构建产物
      uses: actions/upload-artifact@v2
      with:
        name: app-build
        path: app/build/outputs/apk/debug/
